paths:
  /api/quizzes:
      get:
        tags:
          - Quizzes
        summary: Getting Quiz by Tutorial ID
        parameters:
          - name: tutorial_id
            in: query
            schema:
              type: integer
            example: '35408'
          - name: user_id
            in: query
            schema:
              type: integer
            example: '1'
        responses:
          '200':
            description: Successful response
            content:
              application/json: {}


